# Generated by Django 4.2.6 on 2023-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='update_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
